// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnlZWPkaQqfDwkmvRloMHFbZZhmnqa-0',
    appId: '1:725673772998:web:842d1ad2d58288cf9b54c7',
    messagingSenderId: '725673772998',
    projectId: 'classtools-9d1f1',
    authDomain: 'classtools-9d1f1.firebaseapp.com',
    storageBucket: 'classtools-9d1f1.appspot.com',
    measurementId: 'G-52D59C7QSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroeUn_NgspC73sXtK1xHyTz2xbOgKmnw',
    appId: '1:725673772998:android:9f12af86c04a24859b54c7',
    messagingSenderId: '725673772998',
    projectId: 'classtools-9d1f1',
    storageBucket: 'classtools-9d1f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7J9lMzglPi0d1q3Tw19ug1JUhyF8vn14',
    appId: '1:725673772998:ios:2c54b662667888c89b54c7',
    messagingSenderId: '725673772998',
    projectId: 'classtools-9d1f1',
    storageBucket: 'classtools-9d1f1.appspot.com',
    iosBundleId: 'com.example.classtools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7J9lMzglPi0d1q3Tw19ug1JUhyF8vn14',
    appId: '1:725673772998:ios:80ea31564d86072c9b54c7',
    messagingSenderId: '725673772998',
    projectId: 'classtools-9d1f1',
    storageBucket: 'classtools-9d1f1.appspot.com',
    iosBundleId: 'com.example.classtools.RunnerTests',
  );
}
